# param error test
# --output:start
# *
# --output:end

func test(a, b, c) {
  print(a, b, c)
}

test(1, 2)
