# param error test
# --output:start
# *
# --output:end

func test(a, b, c = 5) {
  print(a, b, c)
}

test(1)
