# param error test
# --output:start
# *
# --output:end

func test(a, b) {
  print (a, b)
}

test(5, 6, 8, 9)
